# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import tx_people.fields
import tx_people.utils


class Migration(migrations.Migration):

    dependencies = [
        ('tx_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterIndexTogether(
            name='identifier',
            index_together=set([('identifier', 'scheme')]),
        ),
    ]
